# Linear Systems 

In this post, we will learn how to solve linear systems such as

$$Ax = b $$

In [1]:
import numpy as np 

In [7]:
A = np.array(
    [
        [1, 1, 1, 1],
        [1, 4, 2, 3],
        [4, 7, 8, 9]
    ],
    dtype=np.float32
)

In [9]:
A[1, 0:] -= (A[1, 0]/A[0, 0])*A[0]  # Gaussian elimination
A[2, 0:] -= (A[2, 0]/A[0, 0])*A[0]
A[2, 1:] -= (A[2, 1]/A[1, 1])*A[1, 1:]
A

array([[1., 1., 1., 1.],
       [0., 3., 1., 2.],
       [0., 0., 3., 3.]], dtype=float32)

## Round-off Error

Gaussian elimination is not always numerically stable. In other words, 
it is susceptible to rounding error that may result in an incorrect final matrix. 
Suppose that, due to round-off error, the matrix A has a very small entry 
on the diagonal.

$$A = \begin{bmatrix} 10^{-15} & 1 \\ -1 & 0 \end{bmatrix}$$

Though $10^{-15}$ is essentially zero, instead of swapping the first and 
second rows to put $A$ in REF, a computer might multiply the first row by
$10^{-15}$, then we will have 

$$
A = \begin{bmatrix} 10^{-15} & 1 \\ -1 & 0 \end{bmatrix} \to
\begin{bmatrix} 10^{-15} & 1 \\ 0 & 10^{15}\end{bmatrix}
$$

Round-off error can propagate through many steps in a calculation. 
The NumPy routines that employ row reduction use several tricks to 
minimize the impact of round-off error, but these tricks cannot fix every matrix.

we will perform a series of steps called row operations which preserve the solution of the system while gradually making the solution more accessible. There are three such operations we may perform.

1. Exchange the position of two equations.

2. Multiply an equation by any nonzero number.

3. Replace any equation with the sum of itself and a multiple of another equation.



In [29]:
def row_operation(A:np.ndarray) -> np.ndarray:
    """
    Rwo operation on n matrix A that is invertible and no zeros 
    in the diagonal (this means that A[0, 0] is not 0 for sure, A[1, 1])
    """
    n = A.shape[0]  # A is a square matrix 
    for i in range(n):
        # scale the ith row into the unit one
        A[i, i:] = A[i, i:]/A[i, i]
        # loop over all row elements of column i 
        # start from i+1 to n 
        for j in range(i+1, n):
            # initialize the elementary matrix
            mat = np.eye(n)  
            scalar = -A[j, i]
            mat[j, i] = scalar
            # implement elementary matrix elimination 
            A = mat @ A 
            
    return A

In [30]:
a1 = np.array(
    [
        [1, 1, 1],
        [1, 4, 2],
        [4, 7, 8]
    ],
    dtype=np.float32
)
row_operation(a1)

array([[1.        , 1.        , 1.        ],
       [0.        , 1.        , 0.33333333],
       [0.        , 0.        , 1.        ]])

In [31]:
fooa = np.random.randint(10, size=(4, 4))
row_operation(fooa)

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 0.5       , 1.25      ],
       [0.        , 0.        , 1.        , 1.21428571],
       [0.        , 0.        , 0.        , 1.        ]])